param(
    [string]$RepoRoot = "C:\Users\linki\Documents\PPSSPP\RAC_60FPS"
)

$ErrorActionPreference = "Stop"

$mission = Join-Path $RepoRoot "reports\STATIC-60FPS-COMPLETE-AUDIT-001"
$objects = Join-Path $mission "objects"
$shards = Join-Path $mission "shards"
$raw = Join-Path $mission "raw"
$review = Join-Path $mission "review"

$dirs = @($mission, $objects, $shards, $raw, $review)

foreach ($dir in $dirs) {
    if (-not (Test-Path $dir)) {
        New-Item -ItemType Directory -Path $dir | Out-Null
    }
}

$kitRoot = Split-Path $PSScriptRoot -Parent
$templateRoot = Join-Path $kitRoot "templates"

$copies = @{
    "master_inventory.csv" = "master_inventory.csv"
    "timing_mechanisms.csv" = "timing_mechanisms.csv"
    "patch_candidates.csv" = "patch_candidates.csv"
    "implementation_groups.csv" = "implementation_groups.csv"
    "manual_test_queue.csv" = "manual_test_queue.csv"
    "coverage.md" = "coverage.md"
}

foreach ($entry in $copies.GetEnumerator()) {
    $src = Join-Path $templateRoot $entry.Key
    $dst = Join-Path $mission $entry.Value

    if (-not (Test-Path $dst)) {
        Copy-Item $src $dst
    }
}

$statusSrc = Join-Path $kitRoot "STATUS.md"
$statusDst = Join-Path $mission "STATUS.md"

if ((Test-Path $statusSrc) -and -not (Test-Path $statusDst)) {
    Copy-Item $statusSrc $statusDst
}

$placeholderFiles = @(
    "README.md",
    "agent_log.md",
    "high_priority_findings.md",
    "shared_timing_architecture.md",
    "uncertainties.md",
    "candidate_patches.md"
)

foreach ($name in $placeholderFiles) {
    $path = Join-Path $mission $name
    if (-not (Test-Path $path)) {
        Set-Content -Path $path -Value "# $name`r`n" -Encoding UTF8
    }
}

$disabledIni = Join-Path $mission "candidate_patches_UNVERIFIED.ini.disabled"

if (-not (Test-Path $disabledIni)) {
@"
; UNVERIFIED STATIC CANDIDATES — DO NOT ENABLE AS A COMPLETE PATCH
; Generated by STATIC-60FPS-COMPLETE-AUDIT-001
; Every entry must remain disabled until manually reviewed and tested.
"@ | Set-Content -Path $disabledIni -Encoding UTF8
}

Write-Host ""
Write-Host "STATIC-60FPS-COMPLETE-AUDIT-001 initialized."
Write-Host "Mission directory:"
Write-Host "  $mission"
Write-Host ""
Write-Host "No game binary, PRX, ISO, cheat file or active patch was modified."
