#!/usr/bin/env python3
"""Per-class fixed-step candidate report from scan-decompiled.py output (committable, no code).

Attribution: a function's hits count for every class that reaches it, except
"engine-shared" functions reached by more than SHARED classes, which are listed
once in their own table. Status: STATIC_CANDIDATE_NOT_TIMING_OR_PARITY_PROOF.
Usage: python research/scripts/fixed-step-report.py --scan <scan-summary.json> --out <dir>
"""
import argparse, collections, hashlib, json
from pathlib import Path

SHARED = 12
STEP_KINDS = ('field_accum', 'float_const', 'int_step', 'int_vs_float')

def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument('--scan', type=Path, required=True); ap.add_argument('--out', type=Path, required=True)
    a = ap.parse_args()
    scan = json.loads(a.scan.read_text(encoding='utf-8'))
    funcs = scan['functionsDetail']
    per = collections.defaultdict(lambda: {'functions': [], 'counts': collections.Counter(), 'thresholds': set()})
    shared = []
    for rva, v in funcs.items():
        steps = {k: n for k, n in v['kinds'].items() if k in STEP_KINDS}
        if not steps: continue
        classes = [c for c in v['reachedFrom'] if c != 'ENGINE']
        entry = {'rva': rva, 'update': v['update'], 'usesDelta': v['usesDelta'], 'kinds': steps,
                 'fields': sorted({h['field'] for h in v['hits'] if h['kind'] in STEP_KINDS and h['field']}),
                 'literals': sorted({h['literal'] for h in v['hits'] if h['kind'] in ('float_const', 'int_vs_float') and h['literal'] and len(h['literal']) < 24})}
        if len(classes) > SHARED or (not classes and 'ENGINE' in v['reachedFrom']):
            shared.append({**entry, 'classes': len(classes)})
            continue
        for c in classes:
            per[c]['functions'].append(rva); per[c]['counts'].update(steps)
            per[c]['thresholds'].update(l for l in entry['literals'] if l.startswith('DAT_'))
    ranking = sorted(per.items(), key=lambda kv: -sum(kv[1]['counts'].values()))
    out = {'status': 'STATIC_CANDIDATE_NOT_TIMING_OR_PARITY_PROOF', 'sharedThreshold': SHARED,
           'scanMethodSha256': scan['methodSha256'], 'methodSha256': hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),
           'classes': [{'class': c, 'steps': sum(v['counts'].values()), 'counts': dict(v['counts']),
                        'functions': sorted(set(v['functions'])), 'floatThresholds': sorted(v['thresholds'])} for c, v in ranking],
           'engineShared': sorted(shared, key=lambda e: -e['classes']),
           'functionSteps': {r: {'kinds': {k: n for k, n in v['kinds'].items() if k in STEP_KINDS}, 'usesDelta': v['usesDelta'],
                                 'fields': sorted({h['field'] for h in v['hits'] if h['kind'] in STEP_KINDS and h['field']})}
                             for r, v in funcs.items() if any(k in STEP_KINDS for k in v['kinds'])}}
    a.out.mkdir(parents=True, exist_ok=True)
    (a.out/'level01-fixed-step-candidates.json').write_text(json.dumps(out, indent=1), encoding='utf-8')
    lines = ['# LEVEL_01 fixed-step candidates (static, generated)', '',
             'Status: STATIC_CANDIDATE_NOT_TIMING_OR_PARITY_PROOF. Generated by research/scripts/fixed-step-report.py',
             'from a local mass decompilation (1818 functions reachable from 150 class updates and engine roots).',
             'Kinds: field_accum = field += other field (pos += vel), float_const = field +/- constant,',
             'int_step = integer field +/- 1, int_vs_float = integer counter compared with a float constant.', '',
             '| Class | Steps | field_accum | float_const | int_step | int_vs_float | Float thresholds |', '|---|---:|---:|---:|---:|---:|---|']
    for c in out['classes']:
        k = c['counts']
        lines.append('| %s | %d | %d | %d | %d | %d | %s |' % (c['class'], c['steps'], k.get('field_accum', 0), k.get('float_const', 0),
                     k.get('int_step', 0), k.get('int_vs_float', 0), ', '.join(t.replace('DAT_00', '0x') for t in c['floatThresholds'])))
    lines += ['', '## Engine-shared functions with fixed-step shapes (reached by > %d classes or engine roots)' % SHARED, '',
              '| Function | Classes | Kinds | Fields |', '|---|---:|---|---|']
    for e in out['engineShared'][:60]:
        lines.append('| %s | %d | %s | %s |' % (e['rva'], e['classes'], ', '.join('%s %d' % kv for kv in e['kinds'].items()), ', '.join(e['fields'][:8])))
    (a.out/'LEVEL01-FIXED-STEP-CANDIDATES.md').write_text('\n'.join(lines)+'\n', encoding='utf-8')
    print(json.dumps({'classesWithSteps': len(out['classes']), 'engineShared': len(shared)}))

if __name__ == '__main__':
    main()
