#!/usr/bin/env python3
"""Find integer frame timers in the local full decompilation (static candidates).

A timer field is an integer field offset that some function steps by +-1. For every
class, all functions it reaches (descriptor slots, depth 4) are searched for:
  step sites   field = field +- 1 (countdown/countup)
  init sites   field = <expression with integer literals>  (state durations)
  compares     field compared with an integer literal, or (float)field with DAT_ constant
Literals in init/compare sites are the frame durations that would need doubling at
60 Hz if the step runs once per update. Output (no code text): offsets, function RVAs,
literals. Status STATIC_CANDIDATE_NOT_TIMING_OR_PARITY_PROOF.
Usage: python research/scripts/frame-timers.py --all <dir> --classes <table> --out <dir>
"""
import argparse, collections, hashlib, json, re
from pathlib import Path

INT_LIT = r'(?:0x[0-9a-f]+|\d+)'

def field_of(expr):
    m = re.search(r'\+\s*(0x[0-9a-f]+|\d+)\)\s*$', expr.strip())
    return (hex(int(m.group(1), 0)) if m else None)

def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument('--all', type=Path, required=True); ap.add_argument('--classes', type=Path, required=True)
    ap.add_argument('--out', type=Path, required=True)
    a = ap.parse_args()
    index = json.loads((a.all/'index.json').read_text(encoding='utf-8'))
    callees = {r['rva']: r['callees'] for r in index}
    table = json.loads(a.classes.read_text(encoding='utf-8'))['classes']
    reach = {}
    for c in table:
        seen = {x for x in c['code'] + c['extra'] if x}; frontier = set(seen)
        for _ in range(4):
            frontier = {g for f in frontier for g in callees.get(f, []) if g not in seen}; seen |= frontier
        reach[c['class']] = seen
    texts = {}
    def text(rva):
        if rva not in texts:
            p = a.all/'c'/(rva+'.c'); texts[rva] = p.read_text(encoding='utf-8', errors='replace') if p.exists() else ''
        return texts[rva]
    step_re = re.compile(r'^\s*\*\((?:int|uint|short|ushort|undefined4) \*\)\s*\((.+)\)\s*=\s*\*\((?:int|uint|short|ushort|undefined4) \*\)\s*\(\1\)\s*\+\s*(-?1)\s*;', re.M)
    init_re = re.compile(r'^\s*\*\((?:int|uint|short|ushort|undefined4) \*\)\s*\((.+?)\)\s*=\s*([^;]*%s[^;]*);' % INT_LIT, re.M)
    cmp_re = re.compile(r'\*\((?:int|uint|short|ushort) \*\)\s*\((.+?)\)\s*(<=|<|>=|>|==)\s*(%s)\b' % INT_LIT)
    out = {}
    for c in table:
        cls = c['class']; fields = collections.defaultdict(lambda: {'step': [], 'init': [], 'compare': []})
        for f in sorted(reach[cls]):
            for m in step_re.finditer(text(f)):
                fo = field_of('(' + m.group(1) + ')')
                if fo: fields[fo]['step'].append({'fn': f, 'delta': int(m.group(2))})
        for fo in list(fields):
            for f in sorted(reach[cls]):
                t = text(f)
                for m in init_re.finditer(t):
                    if field_of('(' + m.group(1) + ')') == fo and not re.search(r'\+\s*-?1\s*$', m.group(2)):
                        bare = re.sub(r'\b[A-Za-z_]\w*\b', ' ', m.group(2))   # drop identifiers (iVar3, DAT_...)
                        lits = [x for x in re.findall(INT_LIT, bare) if x not in ('0',)]
                        if lits and 'param' not in m.group(2):
                            fields[fo]['init'].append({'fn': f, 'literals': lits[:6]})
                for m in cmp_re.finditer(t):
                    if field_of('(' + m.group(1) + ')') == fo:
                        fields[fo]['compare'].append({'fn': f, 'op': m.group(2), 'literal': m.group(3)})
        keep = {fo: v for fo, v in fields.items() if v['init'] or any(cmp['literal'] not in ('0', '1') for cmp in v['compare'])}
        if keep: out[cls] = keep
    rec = {'status': 'STATIC_CANDIDATE_NOT_TIMING_OR_PARITY_PROOF', 'methodSha256': hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),
           'classes': out}
    a.out.mkdir(parents=True, exist_ok=True)
    (a.out/'level01-frame-timers.json').write_text(json.dumps(rec, indent=1), encoding='utf-8')
    lines = ['# LEVEL_01 integer frame timers (static, generated)', '',
             'Status: STATIC_CANDIDATE_NOT_TIMING_OR_PARITY_PROOF. Generated by research/scripts/frame-timers.py.',
             'A timer is an integer field stepped by +-1 per call; init literals are durations in 30 Hz frames.', '',
             '| Class | Field | Steps | Init sites (function: literals) | Compares |', '|---|---|---:|---|---|']
    for cls, fs in sorted(out.items()):
        for fo, v in sorted(fs.items()):
            inits = '; '.join('%s: %s' % (i['fn'], ' '.join(i['literals'])) for i in v['init'][:12])
            cmps = '; '.join('%s %s %s' % (x['fn'], x['op'], x['literal']) for x in v['compare'][:4])
            lines.append('| %s | %s | %d | %s | %s |' % (cls, fo, len(v['step']), inits, cmps))
    (a.out/'LEVEL01-FRAME-TIMERS.md').write_text('\n'.join(lines)+'\n', encoding='utf-8')
    print(len(out), 'classes with frame timers;', sum(len(v) for v in out.values()), 'timer fields')

if __name__ == '__main__':
    main()
