#!/usr/bin/env python3
"""Build the FlamerGate experimental plugin with the existing local PSP SDK.

Signatures come from a local signature pack (tools/runtime/level-sigmap.py
capture, under an ignored _local/ directory) and are written into the ignored
build directory as sigs.h; the committed source contains no game bytes.

Usage: python patches/experimental/flamer-gate/build.py --name FG-v0 \
           --pack research/live-tests/_local/sigpack-level01.json
"""
import argparse, hashlib, json, os, shutil, subprocess
from pathlib import Path

HERE = Path(__file__).resolve().parent; REPO = HERE.parents[2]
SDK = REPO/'01-Travail-et-profil-PPSSPP/Overcompensated-Reprise-2026-09-14/toolchains/pspdev-win'
# Site order defines FG_SITE_* indices in sigs.h and fg_state layout.
SITES = [('update', 'flamer.update'), ('latchSet', 'flamer.latchSet'), ('callback', 'flamer.callback'),
         ('latchClear', 'flamer.latchClear'), ('query', 'flamer.query'), ('sharedDelta', 'guard.sharedDelta')]
TRIVIAL = {0x00000000, 0x03E00008}


def digest(p): return hashlib.sha256(Path(p).read_bytes()).hexdigest()


def pick_anchor(w, m, at, key):
    # Fully specified, non-trivial word that is not a stack-frame opcode, closest to the site.
    cands = [k for k in range(len(w)) if m[k] == 0xFFFFFFFF and w[k] not in TRIVIAL and (w[k] >> 16) != 0x27BD]
    if not cands:
        raise SystemExit('no anchor word for ' + key)
    return min(cands, key=lambda k: abs(k - at))


def gen_sigs(pack, out, extra=None):
    lines = ['/* GENERATED by build.py from a local signature pack. Contains game code words: never commit. */',
             '#include <stdint.h>', 'typedef struct { const char *name; const uint32_t *w; const uint32_t *m;'
             ' uint32_t n; uint32_t at; uint32_t anchor; } fg_sig_t;']
    entries = []
    for i, (short, key) in enumerate(SITES):
        sig = pack['sites'][key]
        w, m, at = sig['words'], sig['masks'], pack['before']
        anchor = pick_anchor(w, m, at, key)
        lines.append('static const uint32_t fg_w%d[%d] = {%s};' % (i, len(w), ','.join('0x%08Xu' % x for x in w)))
        lines.append('static const uint32_t fg_m%d[%d] = {%s};' % (i, len(m), ','.join('0x%08Xu' % x for x in m)))
        lines.append('#define FG_SITE_%s %d' % (short.upper(), i))
        entries.append('{"%s", fg_w%d, fg_m%d, %du, %du, %du}' % (short, i, i, len(w), at, anchor))
    lines.append('#define FG_SIG_COUNT %d' % len(SITES))
    lines.append('static const fg_sig_t fg_sigs[FG_SIG_COUNT] = {%s};' % ', '.join(entries))
    # Frame-counter reference windows: the site word is the low half of a lui/lo pair.
    refs = pack['anchors']['frameCounter']['refs']
    if not refs:
        raise SystemExit('pack has no frameCounter references')
    fc = []
    for i, ref in enumerate(refs):
        w, m, at = ref['words'], ref['masks'], pack['before']
        anchor = pick_anchor(w, m, at, 'frameCounter')
        lines.append('static const uint32_t fg_fw%d[%d] = {%s};' % (i, len(w), ','.join('0x%08Xu' % x for x in w)))
        lines.append('static const uint32_t fg_fm%d[%d] = {%s};' % (i, len(m), ','.join('0x%08Xu' % x for x in m)))
        fc.append('{"fc%d", fg_fw%d, fg_fm%d, %du, %du, %du}' % (i, i, i, len(w), at, anchor))
    lines.append('#define FG_FC_COUNT %d' % len(fc))
    lines.append('static const fg_sig_t fg_fc_sigs[FG_FC_COUNT] = {%s};' % ', '.join(fc))
    if extra and extra.get('literals'):
        # FG-v5 literal patches generated offline (research/scripts/make-offline-sigpack.py)
        lines.append('typedef struct { fg_sig_t sig; uint32_t orig; uint32_t repl; uint32_t bit; } wg_lsig_t;')
        ents = []
        for i, (name, lit) in enumerate(sorted(extra['literals'].items())):
            w, m, at = lit['words'], lit['masks'], extra['before']
            anchor = pick_anchor(w, m, at, name)
            lines.append('static const uint32_t wg_lw%d[%d] = {%s};' % (i, len(w), ','.join('0x%08Xu' % x for x in w)))
            lines.append('static const uint32_t wg_lm%d[%d] = {%s};' % (i, len(m), ','.join('0x%08Xu' % x for x in m)))
            ents.append('{{"%s", wg_lw%d, wg_lm%d, %du, %du, %du}, 0x%08Xu, 0x%08Xu, %du}'
                        % (name, i, i, len(w), at, anchor, lit['orig'], lit['repl'], lit['bit']))
        lines.append('#define WG_LSIG_COUNT %d' % len(ents))
        lines.append('static const wg_lsig_t wg_lsigs[WG_LSIG_COUNT] = {%s};' % ', '.join(ents))
    out.write_text('\n'.join(lines) + '\n', encoding='utf-8')


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument('--name', required=True); ap.add_argument('--pack', required=True, type=Path)
    ap.add_argument('--extra-pack', type=Path, help='FG-v5 offline literal pack (ignored _local/)')
    ap.add_argument('--default-mode', type=int, choices=(0, 1), default=0,
                    help='1 arms the gate at load (final delivery); 0 = observe until a tool requests it')
    a = ap.parse_args()
    if not a.name.replace('-', '').isalnum(): raise ValueError('unsafe name')
    build = HERE/'build'/a.name
    if build.exists(): raise RuntimeError('refusing existing build')
    build.mkdir(parents=True)
    pack = json.loads(a.pack.read_text(encoding='utf-8'))
    extra = json.loads(a.extra_pack.read_text(encoding='utf-8')) if a.extra_pack else None
    gen_sigs(pack, build/'sigs.h', extra)
    shutil.copy2(HERE/'gate.c', build/'gate.c'); shutil.copy2(HERE/'stub.S', build/'stub.S')
    env = os.environ.copy(); env['PATH'] = str(SDK/'bin')+os.pathsep+env.get('PATH', '')
    cc = SDK/'bin/psp-gcc.exe'; pspsdk = SDK/'psp/sdk'
    flags = ['-O2', '-G0', '-std=c11', '-Wall', '-Wextra', '-Werror', '-fno-strict-aliasing', '-fno-builtin',
             '-D_PSP_FW_VERSION=660', '-DFG_DEFAULT_MODE=%du' % a.default_mode, '-I.', '-I'+(SDK/'psp/include').as_posix(), '-I'+(pspsdk/'include').as_posix()]

    def run(cmd):
        r = subprocess.run([str(x) for x in cmd], cwd=build, env=env, text=True,
                           stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
        if r.stdout: print(r.stdout, end='')
        if r.returncode: raise RuntimeError('build failed: '+str(cmd[0]))

    run([cc, *flags, '-c', 'gate.c', '-o', 'gate.o'])
    run([cc, '-G0', '-c', 'stub.S', '-o', 'stub.o'])
    run([cc, *flags, '-L'+(SDK/'psp/lib').as_posix(), '-L'+(pspsdk/'lib').as_posix(),
         '-specs='+(pspsdk/'lib/prxspecs').as_posix(), '-Wl,-q,-T'+(pspsdk/'lib/linkfile.prx').as_posix(),
         '-Wl,-zmax-page-size=128', '-nostdlib', '-nostartfiles', 'gate.o', 'stub.o', (pspsdk/'lib/prxexports.o').as_posix(),
         '-lpspuser', '-lpspmodinfo', '-lgcc', '-o', 'patch.elf'])
    run([SDK/'bin/psp-fixup-imports.exe', 'patch.elf'])
    nm = subprocess.run([str(SDK/'bin/psp-nm.exe'), 'patch.elf'], cwd=build, env=env, text=True,
                        stdout=subprocess.PIPE, check=True).stdout
    symbols = {}
    names = ['fg_state', 'fg_ctl', 'fg_gate', 'fg_query_hook', 'fg_clear_hook', 'fg_clear_return']
    if 'fg_reach_hook' in (HERE/'stub.S').read_text(encoding='utf-8'):
        names += ['fg_reach_hook', 'fg_reach_return']
    if 'fg_dmg_hook' in (HERE/'stub.S').read_text(encoding='utf-8'):
        names += ['fg_dmg_hook', 'fg_age_hook']
    if 'wg_dmg_hook' in (HERE/'stub.S').read_text(encoding='utf-8'):
        names += ['wg', 'wg_flag_hook', 'wg_flag_return', 'wg_dmg_hook']
    if 'wg_lit' in (HERE/'gate.c').read_text(encoding='utf-8'):
        names += ['wg_lit']
    for name in names:
        sym = [l.split()[0] for l in nm.splitlines() if l.strip().endswith(' ' + name)]
        if len(sym) != 1: raise RuntimeError(name + ' symbol not found')
        symbols[name] = int(sym[0], 16)
    run([SDK/'bin/psp-prxgen.exe', 'patch.elf', 'patch.prx'])
    package = build/'FlamerGate'; package.mkdir()
    shutil.copy2(build/'patch.prx', package/'patch.prx'); shutil.copy2(HERE/'plugin.ini', package/'plugin.ini')
    manifest = {'status': 'BUILT_EXPERIMENTAL_NOT_RUNTIME_VALIDATED', 'version': a.name,
                'defaultMode': a.default_mode, 'symbols': symbols, 'sites': [s for s, _ in SITES],
                'packSourceSha256': pack['source']['sha256'],
                'extraLiterals': sorted(extra['literals']) if extra else [], 'sourceSha256': digest(build/'gate.c'), 'stubSha256': digest(build/'stub.S'),
                'builderSha256': digest(__file__), 'prxSha256': digest(package/'patch.prx'),
                'prxBytes': (package/'patch.prx').stat().st_size}
    (build/'manifest.json').write_text(json.dumps(manifest, indent=1), encoding='utf-8')
    print(json.dumps(manifest))


if __name__ == '__main__':
    main()
