from pathlib import Path
import csv,json
from collections import defaultdict
from docx import Document
from docx.shared import Cm,Pt,RGBColor
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
ROOT=Path(r'C:\Users\linki\Documents\PPSSPP\Overcompensated-Reprise-2026-09-14')
OUT=Path(r'C:\Users\linki\Documents\PPSSPP\Documentation-Overcompensated-2026-09-15')
SRC=ROOT/'sources-v0.6.0/sources'
def readcsv(p):return list(csv.DictReader(p.open(encoding='utf-8-sig',newline='')))
def newdoc(title,sub):
 d=Document();s=d.sections[0];s.page_height=Cm(29.7);s.page_width=Cm(21);s.top_margin=Cm(1.7);s.bottom_margin=Cm(1.6);s.left_margin=Cm(2);s.right_margin=Cm(2)
 for name in ['Normal','Title','Subtitle','Heading 1','Heading 2']:
  st=d.styles[name];st.font.name='Calibri';st.font.color.rgb=RGBColor(0,0,0)
 n=d.styles['Normal'];n.font.size=Pt(11);n.paragraph_format.space_after=Pt(7);n.paragraph_format.line_spacing=1.08
 for name,size in [('Title',24),('Heading 1',17),('Heading 2',12)]:
  st=d.styles[name];st.font.size=Pt(size);st.paragraph_format.space_after=Pt(7);st.paragraph_format.space_before=Pt(9)
 d.styles['Subtitle'].font.size=Pt(10)
 d.add_paragraph(title,'Title');d.add_paragraph(sub+' • État au 15 septembre 2026','Subtitle')
 f=s.footer.paragraphs[0];f.alignment=2;f.add_run('Overcompensated  |  ').font.size=Pt(9)
 fld=OxmlElement('w:fldSimple');fld.set(qn('w:instr'),'PAGE');f._p.append(fld)
 d.core_properties.title=title;d.core_properties.author='Projet Overcompensated'
 return d
def p(d,t):d.add_paragraph(t)
def h(d,t):d.add_paragraph(t,'Heading 2')
def bullets(d,items):
 for x in items:d.add_paragraph(x,'List Bullet')
def page(d,title):d.add_page_break();d.add_paragraph(title,'Heading 1')
def table(d,heads,rows,widths,size=10):
 t=d.add_table(rows=1,cols=len(heads));t.autofit=False
 for i,v in enumerate(heads):t.rows[0].cells[i].text=v
 for row in rows:
  for c,v in zip(t.add_row().cells,row):c.text=str(v)
 for ri,row in enumerate(t.rows):
  trpr=row._tr.get_or_add_trPr();trpr.append(OxmlElement('w:cantSplit'))
  if ri==0:trpr.append(OxmlElement('w:tblHeader'))
  for ci,c in enumerate(row.cells):
   c.width=Cm(widths[ci]);c.vertical_alignment=1;pr=c._tc.get_or_add_tcPr();sh=OxmlElement('w:shd');sh.set(qn('w:fill'),'E8EEF4' if ri==0 else ('F5F7F9' if ri%2==0 else 'FFFFFF'));pr.append(sh)
   borders=OxmlElement('w:tcBorders')
   for side in ['top','left','bottom','right']:
    el=OxmlElement('w:'+side);el.set(qn('w:val'),'single');el.set(qn('w:sz'),'4');el.set(qn('w:color'),'D9D9D9');borders.append(el)
   pr.append(borders);mar=OxmlElement('w:tcMar')
   for side in ['top','left','bottom','right']:
    el=OxmlElement('w:'+side);el.set(qn('w:w'),'70');el.set(qn('w:type'),'dxa');mar.append(el)
   pr.append(mar)
   for para in c.paragraphs:
    para.paragraph_format.space_after=Pt(3);para.paragraph_format.space_before=Pt(3);para.paragraph_format.line_spacing=1
    for run in para.runs:run.font.size=Pt(size);run.bold=(ri==0)
 return t
def save(d,name):
 for node in list(d.styles.element.iter(qn('w:pBdr')))+list(d.element.iter(qn('w:pBdr'))):
  node.getparent().remove(node)
 d.save(OUT/(name+'.docx'))
s=newdoc('Overcompensated en une page','Synthèse de transmission')
p(s,'Overcompensated est un projet de modification de Ratchet & Clank Size Matters, un jeu PSP mêlant plateformes, combats et mini-jeux. Il vise en priorité un fonctionnement fidèle à 60 images par seconde dans PPSSPP, en conservant la vitesse, les dégâts, les trajectoires et la progression du jeu de référence à 30 images par seconde.')
h(s,'Le problème à résoudre')
p(s,'Le moteur mélange des calculs proportionnels au temps écoulé et des opérations exécutées à chaque image. Doubler la fréquence peut donc doubler une accélération, raccourcir un délai ou multiplier les dégâts. Un affichage à 60 FPS ne garantit pas que le gameplay est correct. Le cas ouvert le plus immédiat est le véhicule de Clank sur Metalis, perçu comme accéléré malgré le patch global installé.')
h(s,'Ce qui existe déjà')
bullets(s,['Une cartographie de 493 sites d’appel, regroupés en 59 familles sur 15 modules ; une instrumentation et des essais historiques sur Pokitaru, Ryllus et Kalidon.','Le plugin v0.6.0-global-experimental.1 intègre le socle 60 FPS, un routage sélectif et des correctifs existants pour les armes, la caméra, les boulons, les débris et les particules. Sa couverture est expérimentale.','Une liaison locale au débogueur de PPSSPP fonctionne. Sources, configurations et traces sont conservées. Sur Metalis, le journal confirme 106 écritures statiques et 36 appels routés ; la fidélité du mini-jeu reste non validée.'])
h(s,'Ce qu’il faut faire en priorité')
p(s,'Capturer les paramètres du véhicule actif sur Metalis dans la fonction identifiée, après revalidation de la session. Le code identifié contient une intégration de vitesse sans delta de temps et des compteurs par appel dans des fonctions voisines. Il faut relier ces mécanismes aux objets actifs, puis tester une correction ciblée en comparaison 30/60 FPS. L’essai WF-029 à une passe a été annulé ; cette famille est revenue à deux passes.')
p(s,'Ensuite : mesurer dégâts continus, mêlée, acide de Kalidon et sauts des ennemis ; élargir les essais à Ratchet sur Dreamtime, à Clank Géant et à Airboard. Caméra, contrôles et menu restent secondaires.')
h(s,'Comment contribuer avec des LLM')
p(s,'Utiliser les modèles pour rechercher dans les preuves, expliquer le code, préparer une hypothèse et instrumenter un test. Chaque conclusion conserve sa source et son degré de validation. Les 600 simulations et 1 294 injections d’échec annoncées à la livraison contrôlent des protections logicielles, pas l’intégralité du jeu. Sources : START_HERE.md, sources v0.6.0 et observation Metalis du 14 septembre dans le dossier de reprise.')
save(s,'01_Synthese_une_page')
b=newdoc('Comprendre Overcompensated','Bases et principes du projet')
h(b,'1 Le jeu et le résultat recherché')
p(b,'Ratchet & Clank Size Matters est une aventure d’action et de plateformes conçue pour la PSP. Le joueur explore des environnements en trois dimensions, saute entre des plateformes, combat avec différentes armes et utilise des gadgets. Ratchet est le personnage des séquences de combat habituelles ; Clank, son compagnon robot, possède aussi des séquences propres. Les boulons servent de ressources à collecter, tandis que les boulons en titane sont des objets particuliers à trouver.')
p(b,'Cette diversité compte : une correction valable pour la course et le saut de Ratchet ne valide pas automatiquement un véhicule, une course Airboard, un boss ou une séquence de Clank Géant. Chaque mode peut faire avancer ses objets selon des règles différentes.')
p(b,'Overcompensated vise une expérience améliorée, avec comme priorité un 60 FPS fidèle. Le travail porte sur l’édition Europe UCES00420, version 1.00, dans PPSSPP 1.19.3 sous Windows. PPSSPP est l’émulateur qui exécute le programme PSP sur le PC ; le plugin du projet modifie certaines instructions et données en mémoire pendant cette exécution.')
h(b,'Ce que signifie fidèle')
p(b,'Une action doit produire le même résultat sur la même durée de jeu : une plateforme termine son trajet au bon moment, une arme consomme ses munitions au bon rythme, un ennemi saute au bon endroit et les événements de progression restent cohérents. L’animation peut présenter davantage d’images intermédiaires tout en conservant ces propriétés.')
h(b,'Le parcours utile aux essais')
p(b,'Les premiers terrains explorés sont Pokitaru, Ryllus et Kalidon. À la première arrivée sur Metalis, le joueur contrôle Clank dans des mini-jeux. Le passage suivant concerne Clank Géant ; Dreamtime fournit ensuite un terrain pour le gameplay habituel de Ratchet. Le scénario de test doit correspondre au personnage et au mode réellement disponibles.')
p(b,'Pour un lecteur familier des LLM, le projet ressemble à une investigation instrumentée sur un programme hérité : corpus de code machine, hypothèses sémantiques, observations en exécution et expériences comparatives. Le jeu n’intègre pas de LLM ; les modèles interviennent dans le travail d’analyse et de développement.')
p(b,'Repères de lecture : page 2, temps du jeu ; page 3, architecture ; page 4, acquis ; page 5, méthode expérimentale ; page 6, priorités et transmission.')
page(b,'2 Pourquoi le passage à 60 FPS change le gameplay')
p(b,'FPS signifie images par seconde. Passer de 30 à 60 FPS divise approximativement par deux l’intervalle entre deux images : de 33,3 à 16,7 millisecondes. Le danger apparaît lorsqu’un calcul suppose que chaque appel représente toujours un trentième de seconde.')
h(b,'Trois mécanismes à reconnaître')
table(b,['Mécanisme','Exemple simplifié','Effet potentiel à 60 FPS'],[['Calcul au temps écoulé','position += vitesse × dt','Correct si dt est adapté et utilisé.'],['Incrément par appel','position += vitesse','Distance par seconde doublée si les appels doublent.'],['Compteur par appel','délai -= 1','30 appels passent de 1 s à 0,5 s si la cadence double.']],[3.7,6,7.3])
p(b,'Ces exemples expliquent le problème ; ils ne sont pas des patchs prêts à installer. Diviser une constante par deux peut corriger un mouvement et casser une collision, un seuil ou un événement. Une accélération agit sur une vitesse, qui agit sur une position : plusieurs étapes peuvent avoir besoin d’un traitement cohérent.')
h(b,'Le socle temporel')
p(b,'L’analyse du projet identifie une boucle avec deux attentes VBlank. VBlank est un repère de synchronisation de l’affichage. Le socle retire une seule de ces attentes, adapte le delta général de 1/30 vers 1/60 et reprend des compensations du joueur et de la caméra. Retirer les deux attentes ne correspond pas à la solution retenue. VBlank, images produites et mises à jour d’un objet sont des mesures distinctes.')
h(b,'Le wrapper et ses passes')
p(b,'Un wrapper est ici une routine intermédiaire appelée par plusieurs parties du jeu. Le projet distingue son chemin à deux passes, TWO_PASS, et son chemin réduit à une passe, ONE_PASS. Le dispatcher choisit le chemin au site d’appel. Ces termes décrivent ce mécanisme particulier ; ils ne veulent pas dire que toute la simulation tourne une ou deux fois.')
p(b,'Certaines opérations sont déjà compensées ailleurs ; d’autres sont exécutées avant ou après le wrapper. Le bon choix dépend du contexte. CUSTOM signale un besoin de traitement spécifique ; dans la v0.6.0 livrée, ces routes retombent sur TWO_PASS. Ce repli ne résout pas automatiquement leur problème temporel.')
page(b,'3 Le système technique et le rôle de chaque pièce')
table(b,['Pièce','Rôle dans le projet'],[['ISO et fichiers extraits','Contiennent le programme et les ressources. Les modules PRX servent à l’analyse statique.'],['PPSSPP','Exécute le jeu et expose son état au débogueur.'],['Plugin PRX','Détecte le module chargé, applique les corrections et compte les appels.'],['Configuration INI','Sélectionne le mode, les couches et les politiques.'],['Liaison locale','Interroge PPSSPP par WebSocket pour identifier le jeu, lire la mémoire ou préparer une capture.'],['Traces et archives','Conservent les preuves et permettent de reprendre une expérience.']],[4,13])
p(b,'Le travail suit une boucle courte : observer une anomalie, chercher le code concerné, mesurer son exécution, proposer une correction limitée, comparer puis conserver le résultat. Analyse des fichiers et observation du jeu se complètent : une fonction présente dans un module peut ne jamais être appelée dans la scène testée.')
h(b,'Pourquoi les adresses changent')
p(b,'Les modules peuvent être chargés à des positions mémoire différentes selon la session et les plugins présents. Une RVA est une adresse relative au début d’un module. Pour retrouver une instruction en mémoire, le système combine cette position relative avec la base observée. Les anciens décalages fixes ne sont pas des règles générales.')
p(b,'Le plugin vérifie les instructions attendues avant de les remplacer. Les écritures sont organisées avec retour arrière en cas d’échec ; le déblocage du rythme intervient en dernier. Les routines ajoutées utilisent la mémoire du plugin. Ces protections limitent les erreurs d’installation ; elles ne démontrent pas que chaque correction est juste pour le gameplay.')
h(b,'Le débogueur et le profileur')
p(b,'La liaison locale lit l’identité du jeu et l’index du module. Un point d’arrêt suspend le processeur émulé à une instruction pour examiner les registres et les objets. Le profileur compte les passages pendant le jeu. Les pauses de débogage peuvent perturber les durées : on sépare la capture d’un état précis du chronométrage d’une action.')
p(b,'Source de principe : PPSSPP, Developer tools, https://www.ppsspp.org/docs/development/developer-tools/. Les capacités effectivement utilisées sont attestées par les sondes locales du projet.')
page(b,'4 Les acquis et leurs limites')
p(b,'La cartographie comprend 493 sites d’appel du wrapper, regroupés en 59 familles sur 15 modules. Une famille rapproche des fonctions de structure similaire ; elle ne garantit ni un usage unique ni une correction identique pour tous ses appelants.')
table(b,['Acquis','Niveau de preuve à retenir'],[['Socle et corrections intégrées','Présents dans la v0.6.0 expérimentale ; validation globale incomplète.'],['119 ONE_PASS et 374 TWO_PASS','Routage livré, confirmé par le rapport de résolution ; comportements non tous validés.'],['Essais des trois premiers niveaux','Couverture historique de 85 sites sur 145 ; certaines preuves restent des comptes rendus.'],['Installation sur Metalis','106 écritures et 36 appels routés attestés par le journal.'],['Véhicule de Clank accéléré','Observation utilisateur malgré l’installation ; facteur ×2 ressenti, non chronométré.'],['Connexion locale à PPSSPP','Version, identité du jeu et lectures mémoire enregistrées.']],[6.1,10.9])
h(b,'La dernière piste sur Metalis')
p(b,'WF-029 avait été envisagée comme responsable du mouvement du véhicule. L’analyse ultérieure indique qu’elle lisse une valeur utilisée dans une rotation. L’essai ONE_PASS a été annulé et TWO_PASS rétabli. La recherche s’est déplacée vers une fonction d’accélération et de freinage, qui ajoute la vitesse aux coordonnées, et vers des compteurs décrémentés par appel dans les objets du mini-jeu.')
p(b,'Il reste à capturer les paramètres réellement utilisés par le véhicule actif. La précédente session mémoire s’est terminée ; les anciennes adresses de plugin et le point d’arrêt doivent être revalidés. Aucun nouveau correctif véhicule n’est à considérer comme validé.')
h(b,'Les autres améliorations')
p(b,'Le mouvement diagonal a été corrigé via AnalogIsCircular=True, avec confirmation utilisateur. La caméra PS2 a été retenue à distance 9,0 et hauteur 1,90, avec champ de vision d’origine, sur Pokitaru. Contrôles supplémentaires, menu et améliorations visuelles ont des états distincts ; ils ne sont pas intégrés comme nouvelles fonctions à la v0.6.0.')
page(b,'5 Comment prouver une correction')
p(b,'Un essai utile répond à une question précise : à configuration et état initial comparables, le véhicule parcourt-il la même distance pendant cinq secondes à 30 et à 60 FPS ? Le résultat doit relier une différence mesurable à une modification identifiée.')
bullets(b,['Fixer version du jeu, plugin et configuration ; enregistrer leurs empreintes et le module réellement chargé.','Partir d’une sauvegarde normale et d’un démarrage propre entre profils. Un ancien savestate peut réintroduire le code et la mémoire d’une autre version.','Définir les entrées, la scène et la durée. À cadence différente, comparer le même nombre d’images ne compare pas la même durée.','Mesurer une grandeur principale et les effets secondaires : distance et collision, cadence et munitions, dégâts par application et nombre d’applications.','Archiver les traces dans un dossier propre à l’essai, puis conclure pour ce scénario uniquement.'])
h(b,'Des résultats qui ne se remplacent pas')
p(b,'Une analyse statique établit ce que le code peut faire. Une trace montre qu’un chemin a été exécuté. Une simulation du patch contrôle ses transactions. Une observation visuelle repère un problème ressenti. Une comparaison 30/60 mesure l’écart de comportement. Chacun apporte une preuve différente ; leur combinaison rend une correction défendable.')
p(b,'Les compteurs peuvent être cumulatifs. Les exports Kalidon 0004 et 0005 contiennent les mêmes 87 570 hits utiles : les additionner créerait une fausse progression. Un compteur nul peut correspondre à un mode de détection sans instrumentation ou à une action jamais déclenchée.')
h(b,'Apport concret des LLM')
p(b,'Un modèle peut retrouver des indices dans les noms de classes, comparer des variantes de fonctions, proposer des instruments et rédiger un patch. Il faut conserver la frontière entre sa proposition et ce que les outils ont vérifié. Un nom plausible attribué à une fonction n’est pas une preuve de sa responsabilité dans le symptôme.')
p(b,'L’intervention humaine reste précieuse pour atteindre les scènes, juger le ressenti et déclencher des comportements difficiles à automatiser. Une transmission utile contient un objectif limité, les fichiers pertinents, l’état du dernier essai et la mesure attendue. Elle évite de reconstruire tout l’historique à chaque reprise.')
page(b,'6 La feuille de route et la reprise')
table(b,['Priorité','Travail','Résultat attendu'],[['1','Capturer le véhicule de Metalis et sa table active.','Relier incréments et compteurs aux objets exécutés.'],['2','Corriger et comparer le mini-jeu à 30 et 60 FPS.','Vitesse, accélération et attaques mesurées ; régressions recherchées.'],['3','Traiter armes continues, mêlée, acide et sauts.','Réduire les différences déjà signalées.'],['4','Étendre aux autres niveaux et modes spéciaux.','Couverture incluant transitions et changements de module.'],['5','Reprendre caméra, contrôles et menu.','Intégration après stabilisation temporelle.']],[1.5,7,8.5])
h(b,'Ce que doit contenir une reprise technique')
p(b,'Le point de départ est START_HERE.md dans Overcompensated-Reprise-2026-09-14. Ses notes récentes remplacent plusieurs paragraphes anciens. sources-v0.6.0 contient le code et les tables ; connection, les captures ; sessions, les observations ; history, sept conversations récupérées. La référence associée à ce dossier fournit une carte des preuves.')
p(b,'Pour Metalis, préparer la capture de a0, a1 et a2 à RVA 0x2AB54 : état du mouvement, objet et table de paramètres selon l’analyse en cours. Vérifier jeu, module, base et instructions attendues. Connect-PPSSPP.ps1 recherche le port courant ; des scripts anciens peuvent encore contenir une adresse de session périmée.')
h(b,'Quand considérer une étape terminée')
p(b,'Une étape est terminée quand la modification est identifiée, que le scénario produit le résultat attendu et que ses limites sont documentées. Pour annoncer un 60 FPS fidèle sur l’ensemble du jeu, il faudra couvrir beaucoup plus de situations. Aucun pourcentage global de jeu corrigé ne peut être déduit des seuls 493 sites cartographiés.')
h(b,'Sources principales')
p(b,'Dossier de reprise : START_HERE.md ; CONTINUITE.md ; sources-v0.6.0/README.md et sources/POLICY_RESOLUTION.json ; sessions/2026-09-14-metalis-global-x2/OBSERVATION.md ; connection/wf029-rollback-result.json. Contexte du jeu : fiche officielle PlayStation de Size Matters, https://store.playstation.com/en-us/product/UP9000-PPSA14431_00-UCUS986330000000.')
save(b,'02_Bases_et_principes')
r=newdoc('Référence du projet Overcompensated','Découvertes correctifs essais et suites')
h(r,'1 État de référence et mode de lecture')
p(r,'Cette référence permet de retrouver ce qui a été identifié, intégré, essayé ou laissé ouvert. Elle conserve un niveau explicatif : les adresses utiles servent de repères pour revenir aux preuves, sans reproduire chaque instruction. La priorité reste le 60 FPS fidèle sur la version Europe UCES00420 du jeu PSP dans PPSSPP 1.19.3 sous Windows.')
table(r,['Statut','Signification'],[['Présent dans le code','Le mécanisme ou le correctif existe dans les fichiers examinés.'],['Observé en jeu','Une trace ou un retour utilisateur atteste le phénomène dans un contexte.'],['Comparaison historique','Une mesure 30/60 est rapportée dans les comptes rendus antérieurs.'],['Hypothèse','Une relation causale ou une identification reste à confirmer.'],['Ouvert','Le test ou la correction nécessaire n’est pas terminé.']],[4.5,12.5])
p(r,'La configuration locale lue pour cette synthèse est global_60fps, allowed_module=0, full_layers=15, instrumentation_enabled=true. Elle appartient à v0.6.0-global-experimental.1. Les notes detect_only ou « archive v0.6 absente » des anciens bilans décrivent une phase antérieure. Le README de livraison affirme aussi que le plugin n’a pas encore été exécuté dans PPSSPP : cela valait à la livraison, avant les essais locaux de septembre.')
h(r,'Le dernier état à transmettre')
p(r,'La précédente session mémoire a pris fin. PPSSPP a ensuite été relancé et sa connexion vérifiée le 15 septembre, avec UCES00420 1.00 reconnu. La capture du véhicule de Metalis reste à faire. WF-029 est revenue à TWO_PASS après un essai temporaire en mémoire ; le message ancien « TEST MEMOIRE ACTIF » ne décrit plus cet état. Aucun nouveau correctif spécifique du véhicule n’est validé. [S1, S5, S6]')
h(r,'Organisation de cette référence')
p(r,'Les sections 2 à 7 présentent architecture, patch global, preuves, anomalies, améliorations annexes et protocole. Vient ensuite le catalogue des 59 familles avec politique livrée et indices statiques. La dernière section donne les sources et les éléments historiques manquants. Les identifiants S renvoient à cette bibliographie locale.')
page(r,'2 Architecture et protections du plugin')
p(r,'Les fichiers extraits comprennent des modules PRX lisibles comme exécutables ELF MIPS. MIPS désigne l’architecture d’instructions de la PSP. Les noms de classes, chemins de sources et chaînes de diagnostic conservés aident à identifier des fonctions. Ils servent d’indices, sans fournir le code source original complet. [S2]')
h(r,'Détection puis relocalisation')
p(r,'Le système reconnaît les profils connus, résout leur base réelle par API avec recherche de secours, puis translate les coordonnées depuis la référence 0x09139D00. Sur la session Metalis étudiée, la base était 0x0914BD00, soit +0x12000. Cette valeur appartient à cette session ; les anciens +0x6000, +0x7000 ou +0x8000 ne constituent pas des décalages universels. [S1, S3, S5]')
h(r,'Routage par appelant')
p(r,'Le wrapper commun reste intact ; les sites d’appel sont redirigés individuellement. L’adresse de retour MIPS, notée ra, aide à reconnaître l’appelant. Une même famille peut servir plusieurs objets. Le catalogue statique ne remplace donc pas une décision par contexte lorsque leurs usages diffèrent. [S3, S4]')
h(r,'Installation et retrait')
p(r,'Le plugin prépare les adresses et réencode les sauts, vérifie les mots attendus, applique les changements sous suspension de l’ordonnanceur PSP et arme le VBlank en dernier. Un échec d’installation entraîne un retour arrière des écritures effectuées. Le retrait restaure seulement les mots reconnus comme appartenant au patch ; un module de nouvelle empreinte interdit une restauration depuis l’ancien contexte. Huit routines ajoutées utilisent la mémoire du plugin. [S3]')
h(r,'JIT et constantes tardives')
p(r,'Le JIT de PPSSPP traduit le code PSP pour l’exécuter efficacement sur le PC. Des mots de classe 0x68xxxxxx ont été rencontrés et peuvent être des marqueurs de l’émulateur. Ils ne doivent pas être assimilés automatiquement à une corruption ; les autres gardes doivent être examinées. [S1, S2]')
p(r,'Le patch surveille 77 constantes initialisées à l’exécution dans le corpus global. Il n’applique une correction que lorsque la valeur attendue est reconnue. Une valeur nulle ou différente reste inchangée. L’intervalle de surveillance est de 100 ms ; trois observations stables sont configurées pour la détection. Vérifier le journal avant de commencer la mesure. [S3, S4]')
page(r,'3 Contenu intégré et couverture des modules')
p(r,'La v0.6.0 combine le dispatcher v0.5.0 et le corpus global v0.2.1. Les couches utilisent un masque : 1 pour le socle, 2 pour les armes, 4 pour les objets destructibles et boulons, 8 pour les particules. La valeur 15 les active toutes ; elle ne signifie pas quinze catégories de correctifs. [S3, S4]')
coverage=readcsv(SRC/'COVERAGE.csv')
table(r,['Module et niveau','Écritures','Constantes','1 passe','2 passes'],[[x['Module'].replace('LEVEL_','L')+' '+x['Niveau'],x['Ecritures statiques'],x['Constantes runtime'],x['Appels ONE_PASS'],x['Appels TWO_PASS']] for x in coverage],[8.2,2.3,2.3,2.1,2.1],9)
p(r,'Ce tableau décrit la couverture livrée, pas une validation par niveau. Le frontend et les modules multijoueur LEVEL_16 à LEVEL_20 sont hors du patch global. Giant Clank et Airboard sont expérimentaux. Dreamtime correspond à LEVEL_05 dans le corpus ; l’index runtime doit néanmoins être relevé lors du test. [S3]')
p(r,'Le rapport compte 119 sites ONE_PASS et 374 TWO_PASS, dont 168 routes CUSTOM ramenées à TWO_PASS. Les 13 familles CUSTOM n’ont pas de nouveau handler spécialisé dans ce dispatcher. Les correctifs d’armes importés s’appliquent dans une couche distincte. Sur Metalis, 13 des 36 sites sont en repli CUSTOM, inclus dans les 28 TWO_PASS. [S4]')
page(r,'4 Résultats conservés et valeur des tests')
table(r,['Étape','Résultat conservé','Limite'],[['Pokitaru','34 sites actifs sur 55 ; 496 697 hits.','Compte rendu historique ; couverture partielle.'],['Ryllus','38 sur 57 ; 122 243 hits, passage avec Clank.','Couverture partielle de scène.'],['Kalidon A','Référence 30 FPS ; 69 173 hits rapportés.','Certaines captures originales manquent.'],['Kalidon B','87 570 hits utiles ; Titanium récupéré.','0004 et 0005 sont cumulatifs et identiques.'],['Trois premiers niveaux','85 sites observés sur 145, dans 32 familles.','Agrégat historique, non recalculé intégralement récemment.'],['Archives récupérées','63 contrôles d’empreinte sans écart ; 15 modules concordants ; 8 configurations.','Identité et cohérence des fichiers.'],['Rapports v0.6.0','600 scénarios simulés ; 1 294 injections d’échec.','Hors émulateur, non rejoués intégralement à la reprise.']],[3.4,7.1,6.5],10)
p(r,'Les sept traces locales revalidées par le parseur v0.4.5 passent ses invariants, sans retour inconnu. Les traces L01, L04 et L22 concernées sont des détections sans instrumentation. La compilation PSP et les suites C/ASan n’ont pas été relancées localement à la récupération ; les rapports livrés restent des preuves historiques. [S1, S2, S7]')
h(r,'Ce que prouve Metalis')
p(r,'Le journal global atteste 106 écritures statiques, pending_constants=0, layers=15, 36 sites, 28 TWO_PASS et 8 ONE_PASS. Aucun refus n’est rapporté dans le journal examiné. Malgré cela, le joueur décrit un véhicule accéléré ×2. Ce facteur est perçu, sans mesure chronométrique par la sonde. [S5]')
p(r,'L’intégration s’installe dans ce contexte, tandis que la compensation du mini-jeu reste insuffisante. Protection contre les mauvaises écritures et fidélité du comportement sont deux critères à tester séparément.')
page(r,'5 Anomalies et pistes de correction')
h(r,'Metalis et les véhicules de Clank')
p(r,'RVA 0x2AB54 gère l’accélération et le freinage puis ajoute une vitesse aux coordonnées XYZ sans delta de temps explicite dans le chemin identifié. ClankBotFlingerVehicle à RVA 0x12AAE8 et ClankElectroTorso à RVA 0x12BEB0 contiennent des compteurs décrémentés de 1 : objet+0x70 et, pour le second, état+0xE4. VehicleController update à RVA 0x1956DC appelle les objets via descripteur+0x1C. Aucune correction kFull4 n’a été repérée dans ces plages. Leur responsabilité exacte requiert la capture en jeu. [S1, S6]')
p(r,'WF-029 comptait 8 096 hits pour 2 024 VBlank dans le relevé cumulé, soit quatre hits par VBlank compté. Ce ratio ne mesure pas à lui seul une vitesse. WF-028 totalisait 1 270 et 514 hits sur deux sites ; WF-013, 6 et 6. WF-029 lisse une valeur utilisée dans une rotation. Le retour à TWO_PASS est enregistré dans wf029-rollback-result.json. [S1, S6]')
h(r,'Armes dégâts et mêlée')
p(r,'Les correctifs existants pour 13 armes ont été intégrés selon les modules concernés. L’audit historique évoque 215 lignes de dégâts et 100 niveaux de progression ; le HTML annoncé n’est pas récupéré. Le classeur et les CSV/INI associés sont conservés. Mesurer dégâts par application, fréquence, durée, munitions, expérience, réactions et superposition des effets. [S1, S8]')
p(r,'Le Brûleur a été signalé comme trop puissant, notamment contre Mungo. Brûleur, Laser et mêlée restent à valider : une animation correcte ne prouve pas que le nombre d’événements de dégâts est correct. known_weapon_patch_candidates.csv contient notamment Lacerator, RYNO/T.E.L.T., Shock Rocket et Sniper Mine ; cet inventaire ne représente pas à lui seul les 13 armes. [S2, S3, S8]')
h(r,'Acide ennemis et événements')
p(r,'WF-044 concerne Lvl3Platform : l’acide reçoit une addition avant le wrapper. La v0.6.0 route cette famille en ONE_PASS, ce qui ne corrige pas nécessairement l’addition extérieure. WF-013, WF-014 et WF-021 sont des helpers d’acteurs/navigation liés notamment aux crabes ; ils restent à TWO_PASS. WF-002 est déjà compensée indirectement par les sous-pas joueur. [S1, S2, S4]')
p(r,'WF-058 est liée à une séquence MungoDrone rapportée à 6,10 s en référence contre 3,05 s à 60 FPS. WF-016 concerne HutDoor et un cycle accéléré. Pour débris et boulons, contrôler trajectoire, rebond, durée de vie et unicité de la récompense. Ces pistes ont des degrés de preuve différents. [S2]')
page(r,'6 Améliorations annexes et décisions conservées')
h(r,'Mouvement et caméra')
p(r,'Le mouvement diagonal est corrigé par AnalogIsCircular=True, confirmé par l’utilisateur et conservé. Un nouveau patch du seuil aérien a été écarté sans anomalie nouvelle. La caméra PS2 retient distance 9,0, hauteur 1,90, décalage horizontal nul et FOV d’origine, évalué historiquement à environ 54,42° vertical. La validation visuelle concerne Pokitaru ; l’extension reste à tester. La caméra d’épaule humoristique a été abandonnée. [S1, S9]')
h(r,'Second stick et commandes')
p(r,'Un prototype v0.1 et ses sources ont été récupérés. Une v0.2 a été annoncée mais son archive n’est pas retrouvée et sa validation utilisateur n’est pas établie. Les retours anciens indiquent un R2 fonctionnel et un retard L2 à diagnostiquer par horodatage. Une courbe quadratique de caméra a été introduite pour les faibles amplitudes. [S1, S9]')
table(r,['Commande','Preset MODERN_PS2 souhaité'],[['L1','Saut'],['L2','Sélection rapide'],['R1','Accroupissement'],['R2','Tir'],['L3','Recentrage sans accroupissement, expérimental'],['R3','Vue subjective']],[3,14],10)
h(r,'Menu et autres fonctions')
p(r,'Le menu souhaité ajoute une entrée indépendante au frontend et à la pause, en conservant CHEATS/SPECIAL et les autres entrées d’origine. Remplacer CHEATS ou détourner l’écran 38 est abandonné. Le premier prototype vise l’interface seule ; l’application des options au prochain chargement est acceptable tant que la bascule à chaud n’est pas validée. Le fichier straddle.junk est présent et constitue une piste de symboles. [S1, S9]')
p(r,'Les shaders ont donné des différences décrites comme subtiles. Un effet d’occlusion plus poussé n’est pas établi ; la contrainte reste les possibilités du jeu, du plugin et de PPSSPP. Caméra libre, statistiques, difficulté simple, seconde sélection rapide, replay de segments et LiveSplit sont des pistes ultérieures. Mode photo, stand de tir et HUD repositionnable ne sont pas prioritaires. [S2, S9]')
p(r,'La v0.6.0 n’ajoute aucun nouveau menu, shader, mapping ni cadrage PS2. Ses corrections de vitesse de caméra sont distinctes du projet de cadrage. [S3]')
page(r,'7 Protocole de reprise et critères de décision')
h(r,'Prochaine expérience sur Metalis')
bullets(r,['Revenir au mini-jeu depuis une sauvegarde normale ; identifier UCES00420 1.00, le module et sa base dans la nouvelle session.','Adapter endpoint et bases des scripts. À RVA 0x2AB54, relever a0, a1, a2 et ra ; lire état du mouvement, objet, table et descripteur.','Relier la table active à vitesse, accélération et freinage ; déterminer la fréquence réelle des compteurs des attaques.','Préparer une modification limitée avec mots attendus, remplacement, retour arrière et hypothèse mesurable ; comparer la même action à 30 et 60 FPS.','Vérifier distance, accélération, freinage, rotation, attaques et collisions, puis transitions et autres usages de la fonction partagée.'])
h(r,'Fiche minimale pour chaque essai')
table(r,['Champ','À conserver'],[['Identité','Jeu, plugin et hash, INI, émulateur, module et base.'],['Départ','Sauvegarde, scène, équipement, difficulté et cible.'],['Question','Hypothèse et mesure principale définies avant l’essai.'],['Mesure','Temps émulé, événements, valeurs initiales/finales et répétitions.'],['Résultat','Traces, observation utilisateur, comparaison et limites.'],['Décision','Conserver, annuler ou approfondir ; prochaine action explicite.']],[3.6,13.4],10)
p(r,'Comparer des états équivalents. diagnostics/detect_only.ini, socle_reference.ini et global_default.ini isolent des couches. Un redémarrage propre est requis entre configurations ; désactiver un cheat ne restaure pas forcément le code déjà écrit. Conserver une copie du profil et de la sauvegarde avant l’essai. [S2, S3]')
p(r,'Arrêter en cas de mauvais module, garde invalide, résolution ambiguë, retour inconnu ou comportement anormal. Une pause de débogage permet une capture, mais n’est pas un chronomètre neutre. Définir la tolérance selon la grandeur mesurée ; aucun seuil universel de fidélité n’a été validé pour ce projet.')
families=readcsv(SRC/'tables/wrapper_families.csv')
pol=json.loads((SRC/'POLICY_RESOLUTION.json').read_text(encoding='utf-8-sig'));routes=defaultdict(set)
for rt in pol['routes']:routes[rt['family_id']].add(rt['configured_policy'])
notes={'WF-002':'Orientation joueur ; compensation indirecte à préserver.','WF-003':'Rail à solliciter.','WF-006':'Polarizer à solliciter.','WF-013':'Navigation et orientation ; contextes multiples dont crabes.','WF-014':'Navigation ; branches et drapeau 0x40 à isoler.','WF-016':'HutDoor ; cycle complet à comparer.','WF-021':'Navigation des crabes ; saut et collision.','WF-024':'Skyboarder01 avant LEVEL_22.','WF-028':'Torses de Clank ; activité observée sur Metalis.','WF-029':'Lissage lié à une rotation ; essai annulé, TWO_PASS rétabli.','WF-030':'TMRobotHeadB à solliciter.','WF-031':'CrankedObject à solliciter.','WF-044':'Lvl3Platform ; addition d’acide avant wrapper.','WF-058':'MungoDrone ; 6,10 s contre 3,05 s rapportées.'}
for start in range(0,len(families),10):
 chunk=families[start:start+10];page(r,'Catalogue des familles '+str(start+1)+' à '+str(min(start+10,len(families))))
 p(r,'Politique = configuration v0.6.0, non verdict de validation. CUSTOM est exécuté par repli TWO_PASS. « confirmed » dans le CSV confirme le regroupement binaire, pas la fidélité du gameplay. Les indices sont des associations statiques : @0 indique la fonction de l’objet, @1 à @3 une proximité de un à trois appels. Seuls trois indices au plus sont affichés par famille. [S2, S4]')
 for x in chunk:
  fid=x['family_id'];policy='/'.join(sorted(routes[fid])).upper();h(r,fid.replace('-',' ')+'   '+policy)
  obj=x['exact_object_descriptors'] or x['object_ancestors_depth_le_3'];obj=' ; '.join(obj.split(';')[:3]) if obj else 'objet non attribué'
  note=notes.get(fid,x['static_domain_hypotheses'] or 'Domaine indéterminé')
  p(r,f"{x['callsite_count']} site{'s' if int(x['callsite_count'])>1 else ''} sur {x['module_count']} module{'s' if int(x['module_count'])>1 else ''}. {note.rstrip('.')}. Indices : {obj}. Attribution : {x['evidence_strength']}.")
page(r,'Sources et éléments à retrouver')
p(r,'Racine : C:/Users/linki/Documents/PPSSPP/Overcompensated-Reprise-2026-09-14. Chemins relatifs à cette racine, sauf mention contraire. Les observations récentes priment sur les états anciens d’installation.')
sources=[('S1','START_HERE.md','État de reprise, notes Metalis, rectifications.'),('S2','CONTINUITE.md','Acquis et anomalies historiques ; installation parfois périmée.'),('S3','sources-v0.6.0/README.md ; sources/COVERAGE.csv ; sources/profiler/src/rcsm_full_patch.c','Contenu livré, couverture et transactions. Les deux derniers chemins partent de sources-v0.6.0.'),('S4','sources-v0.6.0/sources/POLICY_RESOLUTION.json ; sources-v0.6.0/sources/tables/wrapper_families.csv','Routes et catalogue. INI actif dans C:/Users/linki/Documents/PPSSPP/PSP/PLUGINS/SizeMattersWrapperProfiler.'),('S5','sessions/2026-09-14-metalis-global-x2/OBSERVATION.md','Installation et symptôme.'),('S6','connection/wf029-rollback-result.json ; connection/disasm-*.txt ; connection/probe-1789494840843.json','Retour arrière, désassemblages, reconnexion.'),('S7','received-validation/audit.json ; trace-validation/ ; sources-v0.6.0/sources/HOST_VALIDATION.json','Vérifications locales et historiques.'),('S8','supplemental-files/','Classeur armes/ennemis, CSV candidats et INI de test.'),('S9','history/index.json et transcriptions Markdown','Architecture, armes, caméra, menu, contrôles et mouvement.')]
for sid,path,desc in sources:h(r,sid);p(r,path+' — '+desc)
p(r,'À retrouver : Controls v0.2, HTML armes/menu et point d’étape final, certaines vidéos et traces A/B. Les sources v0.5.0 et v0.6.0 sont déjà récupérées. Une pièce reconstruite de mémoire ne remplace pas l’original.')
p(r,'Contexte externe : fiche PlayStation de Size Matters, https://store.playstation.com/en-us/product/UP9000-PPSA14431_00-UCUS986330000000 ; outils PPSSPP, https://www.ppsspp.org/docs/development/developer-tools/. Les conclusions sur le patch reposent sur les sources locales.')
save(r,'03_Reference_decouvertes_et_correctifs')
print(json.dumps({'files':[str(x) for x in OUT.glob('*.docx')],'families':len(families),'callsites':sum(int(x['callsite_count']) for x in families)},ensure_ascii=False))
