_C1 Size Matters - LEVEL_23 Omega Skyboard Base 60 FPS

# VBlank / framerate limiter bypass
# RAM: 091C7420
_L 0x209C7420 0x00000000

# Main delta: 1/30 -> 1/60
# RAM: 0914DB70
# Original: lui a0,0x3D08
# Patch:    lui a0,0x3C88
_L 0x2094DB70 0x3C043C88

# Skyboard/player sub-update loop: 2 iterations -> 1 iteration
# RAM: 091631D8
# Original: slti a0,s1,0x2
# Patch:    slti a0,s1,0x1
_L 0x209631D8 0x2A240001
