_C1 Size Matters - LEVEL_05 Dreamtime Base 60 FPS

# VBlank / framerate limiter bypass
# RAM: 091CEFEC
_L 0x209CEFEC 0x00000000

# Main delta: 1/30 -> 1/60
# RAM: 0914E3E0
# Original: lui a0,0x3D08
# Patch:    lui a0,0x3C88
_L 0x2094E3E0 0x3C043C88

# Ratchet/player sub-update loop: 2 iterations -> 1 iteration
# RAM: 09167708
# Original: slti a0,s1,0x2
# Patch:    slti a0,s1,0x1
_L 0x20967708 0x2A240001
