_C1 Size Matters - LEVEL_03 Kalidon Base 60 FPS

# VBlank / framerate limiter bypass
# RAM: 091D000C
_L 0x209D000C 0x00000000

# Main delta: 1/30 -> 1/60
# RAM: 0914ECD4
_L 0x2094ECD4 0x3C043C88

# Ratchet/player sub-update loop: 2 iterations -> 1 iteration
# RAM: 09167DA4
# Original: slti a0,s1,0x2
# Patch:    slti a0,s1,0x1
_L 0x20967DA4 0x2A200001
