_C1 Size Matters - LEVEL_02 Ryllus Base 60 FPS

# VBlank / framerate limiter bypass
# RAM: 091D6178
# Original: 
_L 0x2009C478 0x00000000

# Main update loop: 2 iterations -> 1 iteration
# RAM: 0914F2E0
# Original: li a0,0x2
# Patch:    li a0,0x1
_L 0x2094F2E0 0x34040001

# Main delta: 1/30 -> 1/60
# RAM: 0914F2E4
# Original: lui a0,0x3D08
# Patch:    lui a0,0x3C88
_L 0x2094F2E4 0x3C043C88
